image: gitpod/workspace-python:latest

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: connect
    before: export DBT_PROFILES_DIR=$GITPOD_REPO_ROOT/profiles/
    init: pip install -r requirements.txt
    command: |
      echo $DBT_SERVICE_ACCOUNT > $GITPOD_REPO_ROOT/profiles/service_account.json
      dbt debug
      gp sync-done dbt-check
      dbt deps
    openMode: split-left
  - name: generate docs
    command: |
      gp sync-await dbt-check
      dbt docs generate
      dbt docs serve --no-browser --port 8080
    openMode: split-right

vscode:
  extensions:
    - ms-python.python
    - mechatroner.rainbow-csv
    - innoverio.vscode-dbt-power-user
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - samuelcolvin.jinjahtml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
